RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

DRIVERS = bbi2c usb_cdc

TARGET = i2cs_test2.bin

SRC = i2cs_test2.c

include ../../boards/sam7hxxx/board.mk
include $(MMCULIB_DIR)/mmculib.mk


