RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

DRIVERS = led pacer ir_sirc

TARGET = ir_sirc_test1.bin

SRC = ir_sirc_rx_test1.c

include ../../boards/sam7hxxx-ir/board.mk
include $(MMCULIB_DIR)/mmculib.mk


