RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

DRIVERS = usb_cdc

TARGET = usb_cdc_test1.bin

SRC = usb_cdc_test1.c

include ../../boards/sam7hxxx/board.mk
include $(MMCULIB_DIR)/mmculib.mk


