RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

DRIVERS = led pacer button 

PERIPHERALS = extint

TARGET = sleep_test1.bin

SRC = sleep_test1.c

include ../../boards/board.mk
include $(MMCULIB_DIR)/mmculib.mk


