RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

DRIVERS = tcm8230 led usb_cdc

TARGET = tcm8230_dump1.bin

SRC = tcm8230_dump1.c

include ../../boards/sam7hxxx-tcm8230/board.mk
include $(MMCULIB_DIR)/mmculib.mk


