RUN_MODE = ROM

OPT = -Os

MMCULIB_DIR = ../../mmculib

DRIVERS = led pacer ir_rc5

TARGET = ir_rc5_test1.bin

SRC = ir_rc5_rx_test1.c

include ../../boards/sam7hxxx-ir/board.mk
include $(MMCULIB_DIR)/mmculib.mk


